### ISSUE TITLE
Include libapache2-mod-auth-openidc in image

### ISSUE THREAD

**Issue by porkotron** [Digital-Identity-Labs/rasp#3]
I have a use case where I need both saml and openid authentication and it would
be nice that the module was preinstalled in the image.

**Comment by binaryape** [comment]
This is a good idea. I'll try to get a new version out by (or at) this weekend.

The module will be included but probably not active by default.

**Comment by binaryape** [comment]
There's a new release of Rasp on Github and Docker Hub (0.4.0) that includes the OpenIDConnect module. It's disabled by default but if you pass and ENV var of `APACHE_EXTRA_MODS="auth_openidc"` it will be enabled before Apache starts. I hope it's OK - please let me know if it works OK or not!

**Comment by porkotron** [comment]
Hi, sorry for the late response but I finally got to test this and it's working fine 
but you need to add ```ShibCompatValidUser on``` to apache configuration if you are going to use with mod_shib enabled.
