### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by porkotron** [Digital-Identity-Labs/rasp#5]
There's couple of CVEs fixed in Apache after versio 2.4.57 so creating a new release with current versions might be appropriate.
I built a local image with current versions (Debian 12.5 / Apache 2.4.59) and everything seems to work ok.

**Comment by binaryape** [comment]
Thanks, I should definitely bump the Apache version - I'll try to get a new release out ASAP.

**Comment by binaryape** [comment]
@porkotron I'm getting `this version of mod_ssl was compiled against a newer library (OpenSSL 3.0.13 30 Jan 2024 (OpenSSL 3.0.11 19 Sep 2023), version currently loaded is 0x300000B0) - may result in undefined or erroneous behavior` errors when Apache starts up, did you get that? I wonder if something is out of sync with the packages now

**Comment by porkotron** [comment]
Seems like debian package building pipeline with openssl is somehow broken  
Found this old still open bug report from the apache2-bin bug reports: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955743 and you can find a lot of chatter online about this kind of problems on debian.
OpenSSL 3.0.13 is currently in the proposed updates: https://release.debian.org/proposed-updates/stable.html#openssl_3.0.13-1~deb12u1 .
Maybe just wait untill that is released?

**Comment by binaryape** [comment]
Oh well spotted, I missed that Debian bug report. I think I'll wait a few days more at least. Cheers!

**Comment by porkotron** [comment]
When building this [open](https://github.com/Digital-Identity-Labs/rasp/pull/6) I noticed that the warning about openssl version is not appearing anymore.

**Comment by binaryape** [comment]
I was still getting the warning, but I've released a new version anyway with the other changes. I'll do another release when the error disappears, hope this is OK.
